# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: space_ship.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10space_ship.proto\"\x9a\x03\n\tSpaceShip\x12\'\n\talignment\x18\x01 \x01(\x0e\x32\x14.SpaceShip.Alignment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\nship_class\x18\x03 \x01(\x0e\x32\x10.SpaceShip.Class\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12$\n\x08officers\x18\x07 \x03(\x0b\x32\x12.SpaceShip.Officer\x1a>\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"-\n\tAlignment\x12\x0b\n\x07NEITHER\x10\x00\x12\x08\n\x04\x41LLY\x10\x01\x12\t\n\x05\x45NEMY\x10\x02\"i\n\x05\x43lass\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x43ORVETTE\x10\x01\x12\x0b\n\x07\x46RIGATE\x10\x02\x12\x0b\n\x07\x43RUISER\x10\x03\x12\r\n\tDESTROYER\x10\x04\x12\x0b\n\x07\x43\x41RRIER\x10\x05\x12\x0f\n\x0b\x44READNOUGHT\x10\x06\"\x84\x01\n\x07Message\x12\x12\n\nlatitude_h\x18\x01 \x01(\x05\x12\x12\n\nlatitude_m\x18\x02 \x01(\x05\x12\x12\n\nlatitude_s\x18\x03 \x01(\x02\x12\x13\n\x0blongitude_h\x18\x04 \x01(\x05\x12\x13\n\x0blongitude_m\x18\x05 \x01(\x05\x12\x13\n\x0blongitude_s\x18\x06 \x01(\x02\x32\x36\n\x05Unary\x12-\n\x11GetServerResponse\x12\x08.Message\x1a\n.SpaceShip\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'space_ship_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPACESHIP']._serialized_start=21
  _globals['_SPACESHIP']._serialized_end=431
  _globals['_SPACESHIP_OFFICER']._serialized_start=215
  _globals['_SPACESHIP_OFFICER']._serialized_end=277
  _globals['_SPACESHIP_ALIGNMENT']._serialized_start=279
  _globals['_SPACESHIP_ALIGNMENT']._serialized_end=324
  _globals['_SPACESHIP_CLASS']._serialized_start=326
  _globals['_SPACESHIP_CLASS']._serialized_end=431
  _globals['_MESSAGE']._serialized_start=434
  _globals['_MESSAGE']._serialized_end=566
  _globals['_UNARY']._serialized_start=568
  _globals['_UNARY']._serialized_end=622
# @@protoc_insertion_point(module_scope)
